blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/<int:pk>/', views.BlogPostView.as_view(), name='blog_post'),
    path('login/', views.BlogLogin.as_view(), name='login'),
    path('logout/', views.BlogLogout.as_view(), name='logout')
]

vitalii_notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models


class BlogPost(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    published_date = models.DateTimeField()

    def __str__(self):
        return self.title

blog/forms.py
from django.forms import CharField, TextInput, PasswordInput
from django.contrib.auth.forms import AuthenticationForm, UsernameField


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=TextInput(attrs={"autofocus": True, "class": "form-control"}))

    password = CharField(
        strip=False,
        widget=PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "class": "form-control"
            }
        ),
    )

blog/views.py
from django.views import generic
from .models import BlogPost
from .forms import LoginForm
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth import views as auth_views

from .models import BlogPost


class IndexView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'blog_post_list'
    login_url = 'blog:login'
    permission_required = 'blog.view_blogpost'

    def get_queryset(self):
        return BlogPost.objects.order_by('-published_date')


class BlogPostView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    model = BlogPost
    template_name = 'blog/blog_post.html'
    login_url = 'blog:login'
    permission_required = 'blog.view_blogpost'


class BlogLogin(auth_views.LoginView):
    next_page = 'blog:index'
    form_class = LoginForm


class BlogLogout(auth_views.LogoutView):
    template_name = 'registration/login.html'
    next_page = 'blog:login'

blog/templates/blog/base.html
{% extends 'bootstrap5/bootstrap5.html' %}
{% load static %}

{% block bootstrap5_extra_head %}
    <link rel="icon" type="image/x-icon" href="{% static 'blog/favicon.png' %}">
{% endblock %}

{% block bootstrap5_title %}
    {% block title %}{% endblock %}
{% endblock %}

{% load bootstrap5 %}

{% block bootstrap5_content %}
    <nav class="navbar navbar-light bg-light">
        <div class="container justify-content-center">
            <a class="navbar-brand h2" href="{% url 'blog:index' %}">Vitalii Notes</a>
        </div>
    </nav>
    <div class="container px-4">
        {% block content %}{% endblock %}
    </div>
{% endblock %}

blog/templates/blog/blog_post.html
{% extends 'blog/base.html' %}
{% load markdownify %}

{% block title %} {{ blogpost.title }} {% endblock %}

{% block content %}
    <div class="row mt-2 justify-content-center">
        <div class="card col-md-8">
            <div class="card-body">
                <h2 class="text-center">{{ blogpost.title }}</h2>
                <p class="fw-lighter text-center">{{ blogpost.published_date|date:'d-m-Y' }}</p>
                <p>{{ blogpost.text|markdownify }}</p>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %} Vitalii Notes {% endblock %}

{% block content %}
    {% for post in blog_post_list %}
        <div class="row mt-2 justify-content-center">
            <div class="card col-md-8">
                <div class="card-body d-flex">
                    <a class="h5 text-decoration-none text-dark me-auto" href="{% url 'blog:blog_post' post.id %}">{{ post.title }}</a>
                    <span class="fw-lighter">{{ post.published_date|date:'d-m-Y' }}</span>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}